[package]
name = "edit"
version = "0.1.0"
authors = ["Max Rosoff me@maxrosoff.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
syntect = "4.4"
