name: Publish

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Compilation
      run: cargo build --verbose
    - name: Run Tests
      run: cargo test --verbose
    - name: Login To crates.io
      run: cargo login ${{ secrets.CRATES_LOGIN }}
    - name: Publish To crates.io
      run: cargo publish
